### ISSUE TITLE
SFTP Backups Not working

### ISSUE THREAD

**Issue by Legit4K** [espidev/ebackup#10]
Sftp backups aren't being stored, I've made sure it was configured properly, I've even manually sshed into it successfully from current machine but the plugin doesn't want to. Below is partial config snippet:
```
ftp:
    enable: true
    path: '~/4/backups/'
    type: sftp # ftp for ftp, sftp for ftp over ssh
    host: 'HIDDEN'
    port: 57928
    user: 'backups'
    pass: 'HIDDEN'
    use-key-auth: false # use key based authentication for sftp (ignores password)
    private-key: '~/.ssh/id_rsa'
    private-key-password: '' # leave blank if the private key has no password
```
